import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import Food from "../components/Food";

export default function Home() {
  const [query, setQuery] = useState("");

  const [container, setContainer] = useState([]);

  const [foodName, setFoodName] = useState("");

  useEffect(() => {
    fetchMe();
  }, [foodName]);

  const onChangeHandler = (e) => {
    setQuery(e.target.value);
  };

  const submitHandler = (e) => {
    e.preventDefault();
    setFoodName(query);
  };

  const fetchMe = () => {
    const options = {
      method: "GET",
      headers: {
        "X-RapidAPI-Key": "6e1c49ff4dmsh573dd70390e49ecp175fb8jsnb6f27cf666cc",
        "X-RapidAPI-Host": "edamam-food-and-grocery-database.p.rapidapi.com",
      },
    };

    fetch(
      `https://edamam-food-and-grocery-database.p.rapidapi.com/parser?ingr=+${query}`,
      options
    )
      .then((response) => {
        return response.json();
      })
      .then((data) => {
        setContainer(data.hints);
        console.log(data);
      })
      .catch((err) => console.error(err));
  };

  return (
    <div className=" bg-teal-600">
      <Head>
        <title>Food App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <form
          onSubmit={submitHandler}
          className="flex justify-center items-center flex-col gap-2 py-20"
        >
          <input
            type="text"
            value={query}
            onChange={onChangeHandler}
            placeholder="Input food name..."
            className=" border-2 rounded-xl h-12 p-5"
          />
          <button
            type="submit"
            className="bg-blue-400 py-1 px-3 rounded-xl cursor-pointer font-bold transition ease-in-out delay-150hover:-translate-y-1 hover:scale-110 hover:bg-indigo-500 duration-300 "
          >
            submit
          </button>
        </form>

        <div className="flex sm:grid grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 2xl:grid-cols-5">
          {container.map((item) => {
            return (
              <Food
                src={item.food.image}
                label={item.food.label}
                category={item.food.category}
              />
            );
          })}
        </div>
      </div>
    </div>
  );
}
